In [35]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [36]:
import tensorflow as tf

In [37]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [38]:
df = pd.read_csv("/content/Churn_Modelling.csv")

In [39]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [40]:
#Divide the features in dependent and independent features
x = df.iloc[:, 3:13]
y = df.iloc[:, 13]


In [41]:
x

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [42]:
# Feature engineering
geography_dummies = pd.get_dummies(x["Geography"])
geography_dummies = geography_dummies.astype(int)

In [43]:
geography_dummies

France  Germany  Spain
0          1        0      0
1          0        0      1
2          1        0      0
3          1        0      0
4          0        0      1
...      ...      ...    ...
9995       1        0      0
9996       1        0      0
9997       1        0      0
9998       0        1      0
9999       1        0      0

[10000 rows x 3 columns]

In [44]:
gender = pd.get_dummies(x["Gender"])
gender = gender.astype(int)

In [45]:
gender

Female  Male
0          1     0
1          1     0
2          1     0
3          1     0
4          1     0
...      ...   ...
9995       0     1
9996       0     1
9997       1     0
9998       0     1
9999       1     0

[10000 rows x 2 columns]

In [46]:
x =pd.concat([x, gender, geography_dummies], axis =1)

In [47]:
x =x.drop(columns ="Geography")
x = x.drop(columns ="Gender")

In [48]:
# Splitting the dataset into training set and test set
from sklearn.model_selection import train_test_split

X_train,X_test,y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=1)

In [49]:
X_train

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
2694          628   29       3  113146.98              2          0   
5140          626   29       4  105767.28              2          0   
2568          612   47       6  130024.87              1          1   
3671          646   52       6  111739.40              2          0   
7427          714   33       8  122017.19              1          0   
...           ...  ...     ...        ...            ...        ...   
2895          621   47       7  107363.29              1          1   
7813          684   63       3   81245.79              1          1   
905           672   45       9       0.00              1          1   
5192          663   39       8       0.00              2          1   
235           763   42       6  100160.75              1          1   

      IsActiveMember  EstimatedSalary  Female  Male  France  Germany  Spain  
2694               1        124749.08       0     1       0        1      0  
5140               0         41104.82       1     0       1        0      0  
2568               1         45750.21       1     0       0        1      0  
3671               1         68367.18       1     0       0        1      0  
7427               0        162515.17       0     1       0        0      1  
...              ...              ...     ...   ...     ...      ...    ...  
2895               1         66799.28       0     1       0        1      0  
7813               0         69643.31       1     0       0        1      0  
905                1         92027.69       1     0       1        0      0  
5192               1        101168.90       1     0       1        0      0  
235                0         33462.94       0     1       0        1      0  

[8000 rows x 13 columns]

**🔁 fit_transform(X_train) vs transform(X_test) — Why the difference?**

> 🧪 fit_transform(X_train):

> fit: Learns the scaling parameters (like mean and standard deviation for StandardScaler) from the training data only.

> transform: Applies those learned parameters to scale X_train.

> 🧪 transform(X_test):
Only uses the parameters learned from X_train (mean, std, min, max, etc.) to scale X_test.

No fitting is done on test data, to avoid data leakage.

In [50]:
X_train

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
2694          628   29       3  113146.98              2          0   
5140          626   29       4  105767.28              2          0   
2568          612   47       6  130024.87              1          1   
3671          646   52       6  111739.40              2          0   
7427          714   33       8  122017.19              1          0   
...           ...  ...     ...        ...            ...        ...   
2895          621   47       7  107363.29              1          1   
7813          684   63       3   81245.79              1          1   
905           672   45       9       0.00              1          1   
5192          663   39       8       0.00              2          1   
235           763   42       6  100160.75              1          1   

      IsActiveMember  EstimatedSalary  Female  Male  France  Germany  Spain  
2694               1        124749.08       0     1       0        1      0  
5140               0         41104.82       1     0       1        0      0  
2568               1         45750.21       1     0       0        1      0  
3671               1         68367.18       1     0       0        1      0  
7427               0        162515.17       0     1       0        0      1  
...              ...              ...     ...   ...     ...      ...    ...  
2895               1         66799.28       0     1       0        1      0  
7813               0         69643.31       1     0       0        1      0  
905                1         92027.69       1     0       1        0      0  
5192               1        101168.90       1     0       1        0      0  
235                0         33462.94       0     1       0        1      0  

[8000 rows x 13 columns]

In [51]:
# standard sclar - standardization or normalization of data
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [52]:
X_train

array([[-0.23082038, -0.94449979, -0.70174202, ..., -0.99850112,
         1.71490137, -0.57273139],
       [-0.25150912, -0.94449979, -0.35520275, ...,  1.00150113,
        -0.58312392, -0.57273139],
       [-0.3963303 ,  0.77498705,  0.33787579, ..., -0.99850112,
         1.71490137, -0.57273139],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ...,  1.00150113,
        -0.58312392, -0.57273139],
       [ 0.13123255,  0.01077067,  1.03095433, ...,  1.00150113,
        -0.58312392, -0.57273139],
       [ 1.1656695 ,  0.29735181,  0.33787579, ..., -0.99850112,
         1.71490137, -0.57273139]])

In [53]:
X_train.shape

(8000, 13)

# ANN

#### Tensorflow -- GOOGLE ----> KERAS was wrapper which lets you effeciently use tensorflow and keras and tensorflow are the same now after a integration
#### PYTORCH ---- FACEBOOK

In [59]:
import tensorflow
import keras

In [61]:
from tensorflow.keras.models import Sequential
# Sequential: A linear stack of layers. You can build a model layer by layer
# by simply adding layers using .add().

from tensorflow.keras.layers import Dense
# Dense: A fully connected (dense) layer where every neuron is connected
# to every neuron in the previous layer. Used for most neural network layers.

from tensorflow.keras.layers import LeakyReLU, PReLU, ELU, ReLU
# Activation layers:
#   - ReLU (Rectified Linear Unit): Outputs max(0, x). Fast and widely used.
#   - LeakyReLU: Similar to ReLU but allows a small gradient for x < 0
#     (helps avoid "dying ReLU" problem).
#   - PReLU (Parametric ReLU): Like LeakyReLU but with a learnable negative slope.
#   - ELU (Exponential Linear Unit): Similar to ReLU but smooths the transition
#     for negative values (can improve training in some cases).

from tensorflow.keras.layers import Dropout
# Dropout: Regularization layer that randomly drops a fraction of neurons
# during training to prevent overfitting.


In [63]:
# Initialize the ANN
classifier = Sequential()  # Create a linear stack of layers

# Input layer and first hidden layer
classifier.add(Dense(units=13, activation="relu", input_dim=13))
# 'units=13': number of neurons (same as number of input features)
# 'input_dim=13': explicitly specify input shape (required for first layer)

# Second hidden layer
classifier.add(Dense(units=7, activation="relu"))

# Third hidden layer
classifier.add(Dense(units=6, activation="relu"))

# Output layer units 1 as we want either 1 or 0
classifier.add(Dense(units=1, activation="sigmoid"))
# 'sigmoid': used for binary classification (output between 0 and 1)


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [67]:
classifier.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

We used binary cross-entropy as the loss function because our task is binary classification—predicting between two classes (e.g., 0 or 1). It measures how well the predicted probabilities match the actual class labels. The Adam optimizer was chosen for its efficiency and adaptive learning rate, which speeds up training and often performs better out of the box. Our input layer has 13 neurons to match the 13 input features, and the output layer has 1 neuron with a sigmoid activation to output a probability for the positive class. We use accuracy as a metric to monitor how often the model correctly predicts the class labels.

In [64]:
optimi = tensorflow.keras.optimizers.Adam(learning_rate=0.01)

make classifier using .add() --> .compile()--> .fit(x_train,y_train) --> we can do early stopping if we want to update in such a way that if the model weights are not updating at all then

In [74]:
callback = keras.callbacks.EarlyStopping(monitor='loss')


In [75]:
model_history = classifier.fit(X_train,y_train, validation_split=0.33, batch_size =10, epochs=100, callbacks =callback )

Epoch 1/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8727 - loss: 0.3162 - val_accuracy: 0.8546 - val_loss: 0.3573
Epoch 2/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8700 - loss: 0.3249 - val_accuracy: 0.8535 - val_loss: 0.3515


In [76]:
model_history.history.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [82]:
# make prediction and evaliate the model
y_pred = classifier.predict(X_test)
y_pred = (y_pred>0.5).astype("int32")


63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


In [83]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [84]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [85]:
cm

array([[1515,   70],
       [ 208,  207]])

In [87]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred)
score

0.861

In [88]:
from sklearn.metrics import f1_score, precision_score, recall_score
f1_score = f1_score(y_test, y_pred)
precision_score = precision_score(y_test, y_pred)
recall_score = recall_score(y_test, y_pred)



In [89]:
print(f1_score, ": f1_score")
print(precision_score, ": precision_score")
print(recall_score, " : recall_score")



0.5982658959537572 : f1_score
0.7472924187725631 : precision_score
0.4987951807228916  : recall_score
